apiVersion: apps/v1
kind: Deployment
metadata:
  name: drone-management
  annotations:
      kubesphere.io/creator: Ilia Avdeev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: drone-management
  template:
    metadata:
      labels:
        app: drone-management
    spec:
      containers:
        - name: drone-management
          image: avdeevilia/drone-management:latest
          resources:
            limits:
              memory: "128Mi"
              cpu: "200m"
            requests:
              memory: "128Mi"
              cpu: "200m"
          ports:
            - name: http
              containerPort: 8888
          env:
            - name: PG_HOST
              value: postgresdb
            - name: PG_PORT
              value: "5432"
            - name: PG_USER
              value: beeline-postgres
            - name: PG_PASSWORD
              value: 12345-very-secret-password
