apiVersion: v1
kind: Service
metadata:
  name: drone-management
  annotations:
    kubesphere.io/creator: Ilia Avdeev
  labels:
    app: drone-management
spec:
  type: LoadBalancer
  ports:
    - port: 8000
      targetPort: 8888
  selector:
    app: drone-management