quarkus:
  datasource:
    db-kind: postgresql
    username: postgres
    password: password
    jdbc:
      url: jdbc:postgresql://localhost:5432/postgres?currentSchema=drone_management
  hibernate-orm:
    database:
      generation: none
  flyway:
    locations: db/migration
    schemas: drone_management
    migrate-at-start: true
    baseline-on-migrate: true
    clean-at-start: true
    out-of-order: true
  http:
    port: 8888

drone-management:
  job:
    drone-lifecycle-management:
      interval: PT18s