quarkus:
  datasource:
    db-kind: postgresql
    username: ${PG_USER}
    password: ${PG_PASSWORD}
    jdbc:
      url: jdbc:postgresql://${PG_HOST}:${PG_PORT}/postgres?currentSchema=drone_management
  hibernate-orm:
    database:
      generation: none
  flyway:
    locations: db/migration
    schemas: drone_management
    migrate-at-start: true
    baseline-on-migrate: true
    clean-at-start: true
    out-of-order: true

drone-management:
  job:
    drone-lifecycle-management:
      interval: PT18s